'''
This script recursively scans the /public_html/newsite folder for
error_log files generated by PHP when exceptions are thrown in a
PHP script. An email is then sent detailing the location of the
error_log files and the contents of the error_log files.

Author: Chad Miller
Last Updated: 9/15/2014
'''

import os, smtplib, sys, time
from email.mime.text import MIMEText

emailbody = []
emailmsg = ""

toEmail = "cmiller86@gatech.edu"
fromEmail = "scripty@gtmn.org"

def sendemail():
	global emailmsg

	msg = MIMEText(emailmsg)
	msg["Subject"] = "Daily PHP Error Report"
	msg["From"] = fromEmail
	msg["To"] = toEmail
	
	s = smtplib.SMTP("localhost")
	s.sendmail(fromEmail, [toEmail], msg.as_string())
	s.quit()

def processFile(path):
	global emailbody

	file = open(path, "r")
	size = float(os.stat(path).st_size) / 1000
	body = "Error found in file: {0} ({1} kb)\n\n".format(path, size)
	
	if size >= 500:	#half a megabyte
		body += "File is too big to write to email!\n"
	else:
		for line in file:
			body += line
	
	emailbody.append(body)
	file.close()

def main(argv):
	global emailmsg

	for root, dirs, files in os.walk("/home1/gtmnorg/public_html/newsite"):
		for file in files:
			if file == "error_log":
				processFile(root + "/" + file)
	
	emailmsg += "Daily error report for {0}:\n\n".format(time.strftime("%A, %B %d, %Y"))
	
	if(len(emailbody) > 0):
		for body in emailbody:
			emailmsg += body
	else:
		emailmsg += "No errors found today!"
	
	sendemail()
	return 0

if __name__ == "__main__":
	sys.exit(main(sys.argv[1:]))
